### ISSUE TITLE
Federation Support

### ISSUE THREAD

**Issue by sgentile** [rfermann/nestjs-prisma-graphql-generator#1]
Is there a way to add support for federation ?

key, extends, external ?

```
type Post @key(fields: "id") {
  id: ID!
  title: String!
  content: String!
  published: Boolean!
  createdAt: String!
  userId: Int
  user: User
}


extend type Query {
  posts: [Post!]!
  post(id: ID!): Post
}

extend type User @key(fields: "id") {
  id: ID! @external
  posts: [Post]
}
```

**Comment by rfermann** [comment]
I think there could be some way do add federation support. I Need to admit though that I'm not familiar with federation. Some guidance would be necessary. 

What would be the exact output you would expect? One federated resolver for each Prisma operation?

**Comment by sgentile** [comment]
I recommend reviewing this page:
https://docs.nestjs.com/graphql/federation

**Comment by rfermann** [comment]
Is this still needed? If yes, feel free to support with suggestions about the expected outcome or even a PR. If it isn't needed anymore, I would close the issue as I don't have valid use cases for that functionality atm.

**Comment by rfermann** [comment]
Closed due to missing use case.
